# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookuser',
            name='pistole',
            field=models.BooleanField(default=False, verbose_name='LP'),
        ),
        migrations.AddField(
            model_name='facebookuser',
            name='rifle',
            field=models.BooleanField(default=False, verbose_name='LG'),
        ),
    ]
