# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20171023_1241_backup'),
        ('backend', '0012_auto_20171023_1241'),
    ]

    operations = [
    ]
