# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_merge_20171024_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShooterResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_id', models.CharField(max_length=64, unique=True, verbose_name='Comp_id')),
                ('weapon', models.CharField(max_length=64, verbose_name='Waffe')),
                ('buli', models.CharField(max_length=64, verbose_name='Liga')),
                ('region', models.CharField(max_length=64, verbose_name='Region')),
                ('host', models.CharField(max_length=64, verbose_name='Ausrichter')),
                ('postion', models.PositiveSmallIntegerField(default=False, verbose_name='Position')),
                ('first_name', models.CharField(max_length=64, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=64, verbose_name='Nachname')),
                ('team_full', models.CharField(max_length=64, verbose_name='Mannschaft')),
                ('team_short', models.CharField(max_length=64, verbose_name='Verein')),
                ('result', models.PositiveSmallIntegerField(default=False, verbose_name='Ergebnis')),
                ('shoot_off', models.CharField(blank=True, max_length=64, null=True, verbose_name='Stechen')),
                ('point', models.BooleanField(default=False, verbose_name='Sieger')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hinzugefügt am')),
            ],
            options={
                'verbose_name': 'Shooter Results',
                'verbose_name_plural': 'Shooter Results',
            },
        ),
    ]
