# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_shooterresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=64, unique=True, verbose_name='Comp ID')),
                ('state', models.CharField(blank=True, max_length=64, null=True, verbose_name='State')),
                ('practice', models.BooleanField(default=False, verbose_name='practice')),
                ('competition', models.BooleanField(default=False, verbose_name='competition')),
                ('shoot_off', models.BooleanField(default=False, verbose_name='shoot_off')),
                ('shoot_off_shot', models.BooleanField(default=False, verbose_name='shoot_off_shot')),
                ('finished', models.BooleanField(default=False, verbose_name='finished')),
                ('push', models.BooleanField(default=False, verbose_name='finished')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hinzugefügt am')),
            ],
            options={
                'verbose_name_plural': 'Competitions',
                'verbose_name': 'Competition',
            },
        ),
    ]
